sibers_test_projects/Models/Employee/EmployeeCreateModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Sibers.ApplicationWeb.Models.Employee
{
    public class EmployeeCreateModel
    {
        public int Id { get; set; }
        /// <summary>
        /// Имя
        /// </summary>

        [Required]
        [DisplayName("Имя")]
        public string FirstName { get; set; }

        /// <summary>
        /// Фамилия
        /// </summary>

        [Required]
        [DisplayName("Фамилия")]
        public string LastName { get; set; }

        /// <summary>
        /// Отчество
        /// </summary>

        [DisplayName("Отчество")]
        public string Patronymic { get; set; }

        /// <summary>
        /// E-Mail
        /// </summary>

        [Required]
        [DisplayName("Электронная почта")]
        [EmailAddress(ErrorMessage = "НОМРАЛЬНО ВВЕДИ")]
        public string EMail { get; set; }
    }
}

sibers_test_projects/Models/Employee/EmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Sibers.ApplicationWeb.Models.Employee
{
    public class EmployeeViewModel
    {
        public int Id { get; set; }

        [DisplayName("Имя")]
        public string FirstName { get; set; }

        /// <summary>
        /// Фамилия
        /// </summary>

        [DisplayName("Фамилия")]
        public string LastName { get; set; }

        /// <summary>
        /// Отчество
        /// </summary>

        [DisplayName("Отчество")]
        public string Patronymic { get; set; }

        /// <summary>
        /// E-Mail
        /// </summary>

        [DisplayName("Электронная почта")]
        public string EMail { get; set; }
    }
}

sibers_test_projects/Controllers/EmployeeController.cs
using Sibers.ApplicationWeb.Models.Employee;
using Sibers.BussinessLogic.DTO;
using Sibers.BussinessLogic.Interfaces;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Sibers.ApplicationWeb.Controllers
{
    public class EmployeeController : Controller
    {
        IEmployeeService employeeService { get; set; }

        public EmployeeController(IEmployeeService es)
        {
            employeeService = es;
        }

        public ActionResult Index()
        {
            return View("ViewAll");
        }

        public ActionResult AllEmployers(string sortOrder, string currentFilter, string strSearch, int? page)
        {
            var employers = employeeService.GetAll().Select(x =>
            new EmployeeViewModel
            {
                Id = x.Id,
                FirstName = x.FirstName,
                LastName = x.LastName,
                Patronymic = x.Patronymic,
                EMail = x.EMail
            });
            return PartialView(employers.ToList());
        }

        // GET: Employee/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Employee/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employee/Create
        [HttpPost]
        public ActionResult Create(EmployeeCreateModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // TODO: Add insert logic here
                    var newEmployee = new EmployeeDTO
                    {
                        FirstName = model.FirstName,
                        LastName = model.LastName,
                        Patronymic = model.Patronymic,
                        EMail = model.EMail
                    };
                    employeeService.Create(newEmployee);

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }
            else
            {
                return View(model);
            }

        }

        // GET: Employee/Edit/5
        public ActionResult Edit(int id)
        {
            var model = employeeService.Get(id);
            var modelEdit = new EmployeeCreateModel
            {
                Id = model.Id,
                FirstName = model.FirstName,
                LastName = model.LastName,
                Patronymic = model.Patronymic,
                EMail = model.EMail
            };
            return View(modelEdit);
        }

        // POST: Employee/Edit/5
        [HttpPost]
        public ActionResult Edit(EmployeeCreateModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // TODO: Add update logic here
                    var modelToUpdate = employeeService.Get(model.Id);
                    modelToUpdate.FirstName = model.FirstName;
                    modelToUpdate.LastName = model.LastName;
                    modelToUpdate.Patronymic = model.Patronymic;
                    modelToUpdate.EMail = model.EMail;
                    employeeService.Update(modelToUpdate);

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    return View();
                }
            }
            return View(model);
        }

        // GET: Employee/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Employee/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

sibers_test_projects/Views/Employee/AllEmployers.cshtml
@model IEnumerable<Sibers.ApplicationWeb.Models.Employee.EmployeeViewModel>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Patronymic)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EMail)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Patronymic)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EMail)
        </td>
        <td>
            @Html.ActionLink("Редактировать", "Edit", new { id = item.Id })
        </td>
    </tr>
}

</table>

sibers_test_projects/Views/Employee/Create.cshtml
@model Sibers.ApplicationWeb.Models.Employee.EmployeeCreateModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Создание записи о работнике</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Patronymic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Patronymic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Patronymic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

sibers_test_projects/Views/Employee/Edit.cshtml
@model Sibers.ApplicationWeb.Models.Employee.EmployeeCreateModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Редактирование записи о работнике</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Patronymic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Patronymic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Patronymic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

sibers_test_projects/Views/Employee/ViewAll.cshtml
<div class="row mb-3">
    @Html.ActionLink("Создать работника", "Create", "Employee", new { @class = "btn btn-primary" })
</div>

<div class="row mb-3">
    @Ajax.ActionLink(
               "Обновить работников",
               "AllEmployers",
                 "Employee",
                new AjaxOptions
                {
                    UpdateTargetId = "UpdateContentDiv",
                    InsertionMode = InsertionMode.Replace,
                    HttpMethod = "GET",
                    OnBegin = "onAjaxBegin",
                    OnComplete = "onAjaxComplete"
                }, new { @class = "btn btn-primary", @id = "AllEmployersReloader" })
    <div id="divLoading" class="HideLoader">
        <div class="lds-spinner"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
    </div>
</div>

<div id="UpdateContentDiv">
</div>

<script type="text/javascript">

    $(document).ready(function () {
        $("#AllEmployersReloader").trigger("click");
    });

    function onAjaxBegin() {
        $("#divLoading").removeClass("HideLoader").addClass("ShowLoader");
    }

    function onAjaxComplete() {
        $("#divLoading").removeClass("ShowLoader").addClass("HideLoader");
    }
</script>

@section scripts{
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")
}