sibers_test_projects/Models/Project/ProjectCreateModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sibers.ApplicationWeb.Models.Project
{
    public class ProjectCreateModel
    {
        /// <summary>
        /// Название проекта
        /// </summary>

        [Required]
        [DisplayName("Проект")]
        public string Name { get; set; }

        /// <summary>
        /// Название компании-заказчика
        /// </summary>

        [Required]
        [DisplayName("Заказчик")]
        public string CustomerCompanyName { get; set; }

        /// <summary>
        /// Название компании-исполнителя
        /// </summary>

        [Required]
        [DisplayName("Исполнитель")]
        public string ExecutingCompanyName { get; set; }


        [Required]
        [DisplayName("Руководитель проекта")]
        public int SelectedChiefId { get; set; }

        /// <summary>
        /// Руководитель проекта
        /// </summary>
        [DisplayName("Руководитель проекта")]
        public IEnumerable<SelectListItem> ProjectChiefs { get; set; }

        /// <summary>
        /// Дата начала проекта
        /// </summary>

        [Required]
        [DisplayName("Дата начала проекта")]
        public DateTime StartDate { get; set; }

        /// <summary>
        /// Дата завершения проекта
        /// </summary>

        [Required]
        [DisplayName("Дата ожидаемого завершения")]
        public DateTime EndDate { get; set; }

        /// <summary>
        /// Приоритет проекта (целочисленное значение >=0)
        /// </summary>

        [Required]
        [DisplayName("Приоритет")]
        public int Priority { get; set; }

        /// <summary>
        /// Текстовый комментарий
        /// </summary>
        [DisplayName("Комментарий")]
        public string Comment { get; set; }

        /// <summary>
        /// Исполнители проекта
        /// </summary>
        public IEnumerable<SelectListItem> ProjectWorkers { get; set; }

        /// <summary>
        /// Исполнители проекта
        /// </summary>
        public SelectListItem SelectedProjectWorkers { get; set; }

        [Required]
        [MinLength(1)]
        [DisplayName("Исполнители (работники)")]
        public int[] SelectedWorkerIds { get; set; }
    }
}

sibers_test_projects/Models/Project/ProjectViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Sibers.ApplicationWeb.Models.Project
{
    public class ProjectViewModel
    {
        public int Id { get; set; }

        /// <summary>
        /// Название проекта
        /// </summary>
        [DisplayName("Проект")]
        public string Name { get; set; }

        /// <summary>
        /// Название компании-заказчика
        /// </summary>
        [DisplayName("Заказчик")]
        public string CustomerCompanyName { get; set; }

        /// <summary>
        /// Название компании-исполнителя
        /// </summary>
        [DisplayName("Исполнитель")]
        public string ExecutingCompanyName { get; set; }

        /// <summary>
        /// Руководитель проекта
        /// </summary>
        [DisplayName("Руководитель проекта")]
        public string ProjectChiefName { get; set; }

        /// <summary>
        /// Дата начала проекта
        /// </summary>
        [DisplayName("Дата начала проекта")]
        public DateTime StartDate { get; set; }

        /// <summary>
        /// Дата завершения проекта
        /// </summary>
        [DisplayName("Дата ожидаемого завершения")]
        public DateTime EndDate { get; set; }

        /// <summary>
        /// Приоритет проекта (целочисленное значение >=0)
        /// </summary>
        [DisplayName("Приоритет")]
        public int Priority { get; set; }

        /// <summary>
        /// Текстовый комментарий
        /// </summary>
        [DisplayName("Комментарий")]
        public string Comment { get; set; }

        /// <summary>
        /// Исполнители проекта
        /// </summary>
        [DisplayName("Исполнители (работники)")]
        public IEnumerable<string> Workers { get; set; }

    }
}

sibers_test_projects/Controllers/ProjectController.cs
using Sibers.ApplicationWeb.Models.Project;
using Sibers.BussinessLogic.DTO;
using Sibers.BussinessLogic.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Sibers.ApplicationWeb.Controllers
{
    public class ProjectController : Controller
    {
        IProjectService projectService { get; set; }
        IEmployeeService employeeService { get; set; }

        public ProjectController(IProjectService ps, IEmployeeService es)
        {
            projectService = ps;
            employeeService = es;
        }

        public ActionResult Index()
        {
            return View("ViewAll");
        }

        public ActionResult AllProjects(string sortOrder)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "name";
            ViewBag.StartDateSortParam = sortOrder == "date" ? "date_desc" : "date";
            ViewBag.PrioritySortParam = sortOrder == "prior" ? "prior_desc" : "prior";
            var asd = projectService.GetAll().ToList();
            var projects = projectService.GetAll().Select(x =>
                new ProjectViewModel
                {
                    Id = x.Id,
                    Name = x.Name,
                    CustomerCompanyName = x.CustomerCompanyName,
                    ExecutingCompanyName = x.ExecutingCompanyName,
                    Comment = x.Comment,
                    ProjectChiefName = employeeService.Get(x.ProjectChiefId)?.FullName,
                    Priority = x.Priority,
                    Workers = x.ProjectWorkersId.Select(w => employeeService.Get(w)?.FullName),
                    StartDate = x.StartDate,
                    EndDate = x.EndDate
                });
            switch (sortOrder)
            {
                case "name_desc":
                    projects = projects.OrderByDescending(s => s.Name);
                    break;
                case "date":
                    projects = projects.OrderBy(s => s.StartDate);
                    break;
                case "date_desc":
                    projects = projects.OrderByDescending(s => s.StartDate);
                    break;
                case "prior":
                    projects = projects.OrderBy(s => s.Priority);
                    break;
                case "prior_desc":
                    projects = projects.OrderByDescending(s => s.Priority);
                    break;
                default:
                    break;
            }

            return PartialView(projects.ToList());
        }

        public ActionResult Create()
        {
            var model = new ProjectCreateModel
            {
                ProjectChiefs = GetAllEmployers(),
                ProjectWorkers = GetAllEmployers()
            };
            return View(model);
        }

        // POST: Employee/Create
        [HttpPost]
        public ActionResult Create(ProjectCreateModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // TODO: Add insert logic here
                    var workers = model.SelectedWorkerIds
                         .Select(x => employeeService.Get(x));

                    var newProject = new ProjectDTO
                    {
                        Name = model.Name,
                        CustomerCompanyName = model.CustomerCompanyName,
                        ExecutingCompanyName = model.ExecutingCompanyName,
                        StartDate = model.StartDate,
                        EndDate = model.EndDate,
                        Comment = model.Comment,
                        Priority = model.Priority,
                        ProjectWorkersId = model.SelectedWorkerIds,
                        ProjectChiefId = model.SelectedChiefId
                    };

                    var createdProject = projectService.Create(newProject);

                    projectService.SetChief(createdProject, employeeService.Get(model.SelectedChiefId));

                    foreach (var worker in workers)
                    {
                        projectService.AddWorker(createdProject, worker);
                    }

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    return new JsonResult() { Data = new { error = ex.Message } };
                }
            }
            else
            {
                model.ProjectChiefs = GetAllEmployers();
                model.ProjectWorkers = GetAllEmployers();

                return View(model);
            }

        }

        private IEnumerable<SelectListItem> GetAllEmployers()
        {
            var allEmployers = employeeService.GetAll()
                .Select(t => new SelectListItem { Value = t.Id.ToString(), Text = t.FullName });
            return allEmployers;
        }

    }
}

sibers_test_projects/Views/Project/AllProjects.cshtml
@model IEnumerable<Sibers.ApplicationWeb.Models.Project.ProjectViewModel>

<table class="table table-striped">
    <tr>
        <th id="nameOrder" class="btn-link">
            @Html.DisplayNameFor(expression: model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerCompanyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExecutingCompanyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProjectChiefName)
        </th>
        <th id="startDateOrder" class="btn-link">
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th id="priorityOrder" class="btn-link">
            @Html.DisplayNameFor(model => model.Priority)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Workers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comment)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerCompanyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExecutingCompanyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectChiefName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Priority)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Workers)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
        </tr>
    }

</table>
<script type="text/javascript">
    $(document).ready(function () {;
        var vb = '';
        $("#nameOrder").click(function () {
            vb = '@(ViewBag.NameSortParm)';
            setNewHref(vb);
            $("#AllProjectsReloader").trigger("click");
        });
        $("#startDateOrder").click(function () {
            vb = '@(ViewBag.StartDateSortParam)';
            setNewHref(vb);
            $("#AllProjectsReloader").trigger("click");
        });
        $("#priorityOrder").click(function () {
            vb = '@(ViewBag.PrioritySortParam)';
            setNewHref(vb);
            $("#AllProjectsReloader").trigger("click");
        });
    });

    function setNewHref(vb) {
        $("#AllProjectsReloader").attr('href', $("#AllProjectsReloader").attr('href')).attr('href', $('#vbSort').val() +'/?sortOrder=' + vb);

    }
</script>

sibers_test_projects/Views/Project/Create.cshtml
@model Sibers.ApplicationWeb.Models.Project.ProjectCreateModel


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Создание записи о проекте</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerCompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerCompanyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerCompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExecutingCompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExecutingCompanyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExecutingCompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedChiefId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SelectedChiefId, new SelectList(Model.ProjectChiefs, "Value", "Text"), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SelectedChiefId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", @id="startDatePicker" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control",   @id="endDatePicker" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedWorkerIds, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(model => model.SelectedWorkerIds, new SelectList(Model.ProjectWorkers, "Value", "Text"), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SelectedWorkerIds, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>
<script type="text/javascript">
    $(function () {
        $('#startDatePicker').datepicker({
            dateFormat: "dd-mm-yy"
        });
        $('#endDatePicker').datepicker({
            dateFormat: "dd-mm-yy"
        });
    });
</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

sibers_test_projects/Views/Project/ViewAll.cshtml
<div class="row mb-3">
    @Html.ActionLink("Добавить проект", "Create", "Project", new { @class = "btn btn-primary" })
</div>
@{ 
    var vbSortRazor = ViewBag.NameSortParm;
}
<input type="hidden" id="vbSort" value="" />
<div class="row mb-3">
    @Ajax.ActionLink(
               "Обновить список проекты",
               "AllProjects",
                 "Project",
                 new { sortOrder = vbSortRazor },
                new AjaxOptions
                {
                    UpdateTargetId = "UpdateContentDiv",
                    InsertionMode = InsertionMode.Replace,
                    HttpMethod = "GET",
                    OnBegin = "onAjaxBegin",
                    OnComplete = "onAjaxComplete"
                }, new { @class = "btn btn-primary", @id = "AllProjectsReloader" })
    <div id="divLoading" class="HideLoader">
        <div class="lds-spinner"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
    </div>
</div>

<div id="UpdateContentDiv">
</div>

<script type="text/javascript">

    var defaultHref = $("#AllProjectsReloader").attr('href', $("#AllProjectsReloader").attr('href')).attr('href');
    $("#vbSort").val(defaultHref);
    $(document).ready(function () {
        $("#AllProjectsReloader").trigger("click");
    });

    function onAjaxBegin() {
        $("#divLoading").removeClass("HideLoader").addClass("ShowLoader");
    }

    function onAjaxComplete() {
        $("#divLoading").removeClass("ShowLoader").addClass("HideLoader");
    }
</script>

@section scripts{
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")
}